#!/bin/bash -e

# filename: cron.sa-learn.sh
# version: 0.000000000000001
# Autore: Ataualpa aka Francesco Ciattaglia
# Attivita' del programma: Addestramento bayesiano di SpamAssassin
# modificare i valori delle variabili in base al proprio sistema!

# indirizzo di sistema a cui inviare l'output di cron
MAILTO=fradeve@inventati.org

# utente sotto cui eseguire i comandi dello script
USER=fradeve
GROUP=wheel

# path del database bayes da istruire
BAYESDIR="\
/home/fradeve/.spamassassin/ \
"

# path delle mailbox ham
HAMDIRS="\
/home/fradeve/.mail/inventati/Sent \
/home/fradeve/.mail/amici \
"

# path della mailbox spam
SPAMDIRS="\
/home/fradeve/.mail/inventati/Spam \
"

# apprendimento per spam
for spamdir in $SPAMDIRS ; do \
if [ -e $spamdir ]; then
echo Mi istruisco con lo spam contenuto nella mailbox $spamdir ; \
nice sa-learn --spam --no-sync --showdots $spamdir/{cur,new} \
--dbpath $BAYESDIR --username=$USER; \
rm $spamdir > /dev/null; \
touch $spamdir; \
chmod 700 $spamdir; \
chown $USER:$GROUP $spamdir
fi
done

# apprendimento per ham
for hamdir in $HAMDIRS ; do \
if [ -e $hamdir ]; then
echo Mi istruisco con gli ham contenuti nella mailbox $hamdir ; \
nice sa-learn --ham --no-sync --showdots $hamdir/{cur,new} \
--dbpath $BAYESDIR --username=$USER
fi
done

# sincronizzazione database
sa-learn --sync --dbpath $BAYESDIR --username=$USER
