---
database_file: /home/fradeve/.timetrap.db
round_in_seconds: 900
append_notes_delimiter: ' '
formatter_search_paths:
- /home/fradeve/.timetrap/formatters
default_formatter: text
default_command: 
auto_checkout: false
require_note: false
day_length_hours: 8
progress_width: 15
