session_name: base
start_directory: /home/fradeve
windows:
    - window_name: main
      layout: main-vertical
      options:
          automatic-rename: on
          main-pane-width: 100
      panes:
          - weechat
          - ssh -t zerzan 'mutt'
          - vim -c "TW"
