session_name: base
start_directory: /home/fradeve
windows:
    - window_name: personal
      layout: tiled
      options:
          automatic-rename: on
          main-pane-width: 120
      panes:
          # - shell_command:
          #    - task work
          - shell_command:
              - ssh zerzan
              - mutton
          - shell_command:
              - clear && task tech
          - shell_command:
              - ta
          - shell_command:
              - tc
    - window_name: music
      focus: false
      options:
          automatic-rename: on
      panes:
          - ncmpcpp
