session_name: base
start_directory: /home/fradeve
windows:
    - window_name: ps-mail
      focus: true
      layout: main-horizontal
      options:
          automatic-rename: on
          main-pane-height: 40
      panes:
          - mutton
          - ssh -t moon 'mutt -n -F /home/fradeve/.mutt/muttonrc'
    - window_name: chat
      focus: true
      layout: main-vertical
      options:
          automatic-rename: on
          main-pane-width: 150
      panes:
          - weechat-curses
    - window_name: music
      layout: main-horizontal
      options:
          automatic-rename: on
          main-pane-height: 55
      panes:
          - sleep 5 && ncmpcpp -h moon.ydns.eu -p 6600
          - ncmpcpp
