session_name: base
start_directory: /home/fradeve
windows:
    - window_name: personal
      layout: main-vertical
      options:
          automatic-rename: on
          main-pane-width: 120
      panes:
          - shell_command:
              - ssh zerzan
              - mutton
          - shell_command:
              - clear && task general
          - shell_command:
              - clear && tc
    - window_name: music
      focus: false
      layout: main-vertical
      options:
          automatic-rename: on
      panes:
          - ncmpcpp
