session_name: base
start_directory: /home/fradeve
windows:
    - window_name: ps-mail
      focus: false
      layout: tiled
      options:
          automatic-rename: on
      panes:
          - mutt
          - ssh -t emmett 'vit work'
          - ssh -t moon 'mutt -n -F /home/fradeve/.mutt/muttonrc'
          - ssh -t emmett 'vit general'
    - window_name: chat
      focus: false
      layout: main-vertical
      options:
          automatic-rename: on
          main-pane-width: 150
      panes:
          - weechat-curses
          - ncmpcpp -h moon-fradeve.duckdns.org -p 6600
