session_name: base
start_directory: /home/fradeve
windows:
    - window_name: work
      layout: main-vertical
      options:
          automatic-rename: on
          main-pane-width: 150
      panes:
          - mutt
    - window_name: personal
      layout: main-vertical
      options:
          automatic-rename: on
          main-pane-width: 150
      panes:
          - shell_command:
              - ssh emmett
              - tmux attach -t base
    - window_name: music
      focus: false
      layout: main-vertical
      options:
          automatic-rename: on
          main-pane-width: 150
      panes:
          - ncmpcpp -h moon-fradeve.duckdns.org -p 6600
