session_name: base
start_directory: /home/fradeve
windows:
    - window_name: ps-mail
      panes:
          - mutton
    - window_name: task
      options:
          automatic-rename: on
      shell_command_before:
          - ssh fradeve@emmett
      panes:
          - shell_command: twn
    - window_name: inventati
      panes:
          - ssh -t moon 'mutt -n -F /home/fradeve/.mutt/muttonrc'
    - window_name: music
      panes:
          - ncmpcpp -h moon.ydns.eu -p 6600
    - window_name: vlc
      panes:
          - vlc -vvv --intf dummy http://moon.ydns.eu:8080
