session_name: base
start_directory: /home/fradeve
windows:
    - window_name: ps-mail
      panes:
          - mutton
    - window_name: tasks
      panes:
          - ssh -t emmett 'tw'
    - window_name: inventati
      panes:
          - ssh -t moon 'mutt -n -F /home/fradeve/.mutt/muttonrc'
    - window_name: music
      panes:
          - ncmpcpp -h moon.ydns.eu -p 6600
    - window_name: vlc
      panes:
          - vlc -vvv --intf dummy http://moon.ydns.eu:8080
