# base settings

library:                /home/fradeve/data/music/beets.db
directory:              /home/fradeve/data/music

import:
    write:              yes              # write metadata in files
    move:               yes
    delete:             no
    log:                /home/fradeve/data/music/beets.log
    detail:             yes
    flat:               no
    group_albums:       no

statefile:              state.pickle
threaded:               yes
timeout:                5.0

# file paths settings

clutter:                ["Thumbs.DB", ".DS_Store"]
ignore:                 [".*", "*~", "System Volume Information"]

per_disc_numbering:     no

paths:
    default:            %left{$albumartist,1}/$albumartist/$album%aunique{}/$track $title
    singleton:          %left{$albumartist,1}/$albumartist/non-album/$album%aunique{}/$track $title
    comp:               compilations/$album%aunique{}/$track $title

# filenames and strings

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
path_sep_replace:       _
art_filename:           cover
max_filename_length:    0

# user interface

verbose:                no
terminal_encoding:      utf8
id3v23:                 no

ui:
    color:              yes
    terminal_width:     80
    length_diff_thresh: 10.0

format_item:            $artist - $album - $title - $year
format_album:           $albumartist - $album - $year

# times and date

original_date:          yes
time_format:            '%Y-%m-%d %H:%M:%S'

## plugins settings ###
#######################

pluginpath: []
plugins: [
    lastgenre,
    mbsync,
    scrub,
    missing,
    chroma,
    bpd,
    duplicates,
    embedart,
    fetchart,
    acousticbrainz,
    convert,
]

# mbsync

musicbrainz:
    host: musicbrainz.org
    ratelimit: 1
    ratelimit_interval: 1.0

match:
    strong_rec_thresh: 0.04
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30

# lastgenre

lastgenre:
    source: track
    count: 3
